use_frameworks!

platform :ios, '8.0'

target 'LBYNetworking_Example' do
  pod 'LBYNetworking', :path => '../'

  target 'LBYNetworking_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
  end
end
